name: "Upstream Sync"
on:
  schedule:
    - cron: "0 */4 * * *" # 每4小时运行一次

  workflow_dispatch: # click the button on Github repo!
    inputs:
      debug:
        description: "Fork Sync Test Mode"
        type: string
        default: "true"

jobs:
  call-workflow-sync:
    uses: aliuq/workflows/.github/workflows/sync.yml@master
    with:
      ref: master
      target_sync_branch: master
      upstream_sync_branch: master
      upstream_sync_repo: ccbikai/Sink
      debug: ${{ inputs.debug }}
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
