name: Sync Fork with Upstream

on:
  schedule:
    - cron: '0 */4 * * *' # 每4小时运行一次
  workflow_dispatch: # 手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          ref: master

      - name: Setup Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add Upstream
        run: git remote add upstream https://github.com/ccbikai/Sink.git

      - name: Fetch Upstream
        run: git fetch upstream

      - name: Check for changes
        id: changes
        run: |
          git fetch upstream master
          UPSTREAM_REF=$(git rev-parse upstream/master)
          LOCAL_REF=$(git rev-parse HEAD)
          if [ "$UPSTREAM_REF" != "$LOCAL_REF" ]; then
            echo "Changes detected"
            echo "changes_detected=true" >> $GITHUB_OUTPUT
          else
            echo "No changes detected"
            echo "changes_detected=false" >> $GITHUB_OUTPUT
          fi

      - name: Merge Upstream changes && Push changes
        if: steps.changes.outputs.changes_detected == 'true'
        run: |
          git merge upstream/master --allow-unrelated-histories
          git push origin master

      - name: Send POST request
        if: steps.changes.outputs.changes_detected == 'true'
        run: |
          curl -X POST "${{ secrets.WEBHOOK_URL }}"
